service: sample-project

plugins:
  - serverless-auto-swagger
  - serverless-plugin-typescript
  - serverless-plugin-warmup
  - serverless-offline

provider:
  name: aws
  region: ap-northeast-2
  stage: dev
  runtime: nodejs18.x

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
         method: any
         path: /{any+}